package com.io.appioweb.adapters.web.atendimentos.response;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

public record ConversationHttpResponse(
        UUID id,
        String phone,
        String displayName,
        String photoUrl,
        String sourcePlatform,
        String sourceReference,
        String status,
        UUID assignedTeamId,
        String assignedTeamName,
        UUID assignedUserId,
        String assignedUserName,
        String assignedAgentId,
        Boolean humanHandoffRequested,
        String humanHandoffQueue,
        Boolean humanUserChoiceRequired,
        Instant startedAt,
        String presenceStatus,
        Instant presenceLastSeen,
        String lastMessage,
        Instant lastAt,
        Boolean lastMessageFromMe,
        String lastMessageStatus,
        String lastMessageType,
        UUID sessionId,
        Instant arrivedAt,
        Instant firstResponseAt,
        Instant completedAt,
        String classificationResult,
        String classificationLabel,
        Boolean saleCompleted,
        UUID soldVehicleId,
        String soldVehicleTitle,
        Instant saleCompletedAt,
        Instant latestCompletedAt,
        String latestCompletedClassificationResult,
        String latestCompletedClassificationLabel,
        Boolean latestCompletedSaleCompleted,
        UUID latestCompletedSoldVehicleId,
        String latestCompletedSoldVehicleTitle,
        List<ConversationLabelHttpResponse> labels
) {}
